name: uix_minesweeper
version: 0.0.1
author: Minesweeper
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.9.1'
dependencies:
  browser: any
  uix:
    git: git://github.com/localvoid/uix.git
